language: ruby

rvm:
  - 2.1

before_install:
  - bundle install
  - bourbon install --path=css

install:
  - npm install

script: jekyll build

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer