# Site settings
title: "sanus|art"
email: "sanusart@gmail.com"
description: "Sanus Artificium - free software for music creation, music downloads, sound engineering information, a few how to's, PHP, JavaScript and web development stuff in general"
author: '<a target="_blank" href="https://plus.google.com/111862979601357461785" rel="publisher">Sasha Khamkov</a>'
highlighter: pygments

url: "https://www.sanusart.com"
baseurl: "https://www.sanusart.com"

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: _site

markdown: kramdown
permalink: pretty
excerpt_separator: <!--more-->

include: ['_pages','_codes','graphics','vsts','.htaccess']
exclude: [js/style.js, css/style.scss, css/style.css, css/style.css.map, .gitignore, .bowerrc, package.json, gulpfile.js, node_modules, assets, README.md, bower.json, Gemfile.lock, Gemfile]

collections:
  codes:
    output: true
  vsts:
    output: true
  graphics:
    output: true

gems:
  - jekyll-sitemap