# Site settings
title: sanus|art
email: sanusart@gmail.com
description: "Description"
year: 2014
highlighter: pygments
url: "http://dev.sa.com"

author: '<a target="_blank" href="https://plus.google.com/111862979601357461785" rel="publisher">Sasha Khamkov</a>'

baseurl: ""
port:    4000
host:    0.0.0.0

markdown: kramdown
permalink: pretty

include: [.htaccess]
exclude: [.gitignore, .bowerrc, jmk, package.json, gulpfile.js, node_modules]

collections:
  codes:
    output: true
  vsts:
    output: true
