# Site settings
title: sanus|art
email: sanusart@gmail.com
description: "Description"
baseurl: ""
year: 2014
highlighter: true
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty