# Site settings
title: "sanus|art"
email: "sanusart@gmail.com"
description: "Sanus Artificium - free software for music creation, music downloads, sound engineering information, a few how to's, PHP, JavaScript and web development stuff in general"
year: "2014"
author: '<a target="_blank" href="https://plus.google.com/111862979601357461785" rel="publisher">Sasha Khamkov</a>'
highlighter: pygments

url: "https://www.sanusart.com"
baseurl: "https://www.sanusart.com"

markdown: kramdown
permalink: pretty

include: [.htaccess]
exclude: [js/main.js, css/main.scss, css/main.css, css/main.css.map, .gitignore, .bowerrc, package.json, gulpfile.js, node_modules, assets, README.md, bower.json, Gemfile.lock, Gemfile]

collections:
  codes:
    output: true
  vsts:
    output: true
  graphics:
    output: true

gems:
  - jekyll-sitemap