#!/bin/sh

DATE=$(date +"%Y-%m-%d");

show_usage() {
    echo -e "----------------------";
    echo -e " jmk - create pages and posts faster from CMD";
    echo -e "----------------------";
    echo -e "\tCrete page:\t\t - 'jmk page pagename'";
    echo -e "\tCrete post:\t\t - 'jmk post postname'";
    echo -e "\tCrete custom post:\t - 'jmk _custom_post_name postname'";
}

create_file() {
    touch "$2.md"
    echo "---
layout: $1
title: $2
page_name: $2

category: none
category_url: /$2/

seo_title: $2 page
seo_description: $2 page

permalink: /$2/
---

This is first paragraph" >> "$2.md"
}

if [ -z "$1" ]
    then show_usage;
#elif [ -f  "$1.md" ]
#    then echo -e "$1.md exists"
elif [ $1 = "page" ]
    then echo -e "Create page $2.md"
    create_file 'page' $2
elif [ $1 = "post" ]
    then echo -e "Create post $2.md"
    create_file 'post' "_posts/$DATE-$2"
else
    show_usage;
fi

